apiVersion: apps/v1
kind: Deployment
metadata:
  name: ny-rental
spec:
  selector:
    matchLabels:
      app: ny-rental
  replicas: 2
  template:
    metadata:
      labels:
        app: ny-rental
    spec:
      containers:
        - name: ny-rental
          image: 16francej/ny-rentals:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: database